# Generated by Django 4.0.3 on 2022-03-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='importado',
            field=models.BooleanField(default=False, verbose_name='produto importado'),
        ),
    ]
